export const DISPLAY_TYPES_REPORTS_INPUT_MESSAGES =
  "DISPLAY_TYPES_REPORTS_INPUT_MESSAGES";
export const DISPLAY_TYPES_REPORTS_OUTPUT_MESSAGES =
  "DISPLAY_TYPES_REPORTS_OUTPUT_MESSAGES";
export const DISPLAY_TYPES_REPORTS_IZVOD = "DISPLAY_TYPES_REPORTS_IZVOD";
export const STORE_USER = "STORE_USER";
export const DELETE_USER = "DELETE_USER";
